name: stride
description: Discipline and habit-building app powered by quests and streaks.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # SVG support
  flutter_svg: ^2.0.10

  # Animations
  lottie: ^3.1.0

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/illustrations/
    - assets/illustrations/onboarding/
